repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml

- repo: local
  hooks:
  - id: pylint
    name: pylint
    entry: pylint
    language: system
    types: [python]
    args: [--rcfile=pyproject.toml]

  - id: flake8
    name: flake8
    entry: flake8
    language: system
    types: [python]
    args: [--toml-config=pyproject.toml]

  - id: autopep8
    name: autopep8
    entry: autopep8
    language: system
    types: [python]
    args: [--global-config=pyproject.toml, --in-place]
